---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Update the local file system CRUD
  file:
    src: "{{ item.src|default(omit) }}"
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    force: "{{ item.force|default(omit) }}"
  with_items:
    - { path: "/etc/mysql", state: "directory" }
    - { path: "/etc/mysql/conf.d", state: "directory" }
    - { src: "/usr/lib64/galera", path: "/usr/lib/galera", state: "link", force: true }
    - { src: "/etc/mysql/conf.d", path: "/etc/my.cnf.d", state: "link", force: true }
    - { src: "/etc/mysql/my.cnf", path: "/etc/my.cnf", state: "link", force: true }

- name: If a keyfile is provided, copy the gpg keyfile to the key location
  copy:
    src: "{{ item.keyfile }}"
    dest: "{{ item.key }}"
    mode: '0644'
  with_items: "{{ galera_gpg_keys | selectattr('keyfile','defined') | list }}"

- name: Install gpg keys
  rpm_key:
    key: "{{ key.key }}"
    validate_certs: "{{ key.validate_certs | default(omit) }}"
    state: "{{ key.state | default('present') }}"
  with_items: "{{ galera_gpg_keys }}"
  loop_control:
    loop_var: key
  register: _add_yum_keys
  until: _add_yum_keys is success
  retries: 5
  delay: 2

- name: Add galera repo
  yum_repository:
    name: "{{ galera_repo.name }}"
    description: "{{ galera_repo.description }}"
    baseurl: "{{ galera_repo.baseurl }}"
    gpgkey: "{{ galera_repo.gpgkey | default(omit) }}"
    gpgcheck: yes
    enabled: yes
  register: add_repos
  until: add_repos is success
  retries: 5
  delay: 2

# When changing the repo URL, the metadata does
# not reliably update, resulting in the right
# URL being used, but the wrong package list.
# This is why we force the metadata to be
# cleaned out whenever the repo config changes.
- name: Force the expiry of the repo metadata
  command: "{{ ansible_pkg_mgr }} clean metadata"
  args:
    warn: no
  when: add_repos is changed
  tags:
    - skip_ansible_lint

- name: Install percona repo
  yum_repository:
    name: 'percona-release-$basearch'
    description: 'Percona-Release YUM repository - $basearch'
    baseurl: "{{ galera_percona_xtrabackup_repo.repo }}"
    enabled: true
    gpgcheck: true
    state: "{{ galera_percona_xtrabackup_repo.state }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

# NOTE(mhayden): MariaDB/percona repositories are prioritized at 99 by default
# and that allows yum to install galera from the RDO repos, which is not good.
# This task ensures that the following task will choose MariaDB/percona repos
# as the highest priority.
- name: Ensure MariaDB/percona repositories take highest priority
  command: |
    yum-config-manager
      --enable {{ item }}
      --setopt="{{ item }}.priority=25"
  with_items:
    - MariaDB
    - percona-release-noarch
    - percona-release-x86_64

- name: Install galera_server role remote packages
  package:
    name: "{{ galera_packages_list }}"
    state: "{{ galera_server_package_state }}"
  register: install_remote_packages
  until: install_remote_packages is success
  retries: 5
  delay: 2
